# Generated by Django 3.0.4 on 2020-11-30 09:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itn', '0002_auto_20201130_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayevent',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nightevent',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
