# Generated by Django 3.0.4 on 2020-11-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itn', '0003_auto_20201130_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayevent',
            old_name='content',
            new_name='day_content',
        ),
        migrations.RenameField(
            model_name='nightevent',
            old_name='content',
            new_name='night_content',
        ),
    ]
