# Generated by Django 3.0.4 on 2020-12-01 08:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itn', '0004_auto_20201130_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayevent',
            name='day_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nightevent',
            name='night_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
