# Generated by Django 3.0.4 on 2020-12-01 09:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itn', '0005_auto_20201201_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayevent',
            name='day_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nightevent',
            name='night_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
