# Generated by Django 3.0.9 on 2020-12-08 07:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itn', '0008_auto_20201204_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayevent',
            name='day_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nightevent',
            name='night_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
