# Generated by Django 3.0.9 on 2020-12-17 00:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itn', '0009_auto_20201208_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayevent',
            name='editor',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nightevent',
            name='editor',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
